### ISSUE TITLE
Other common shapes?

### ISSUE THREAD

**Issue by megashub** [jsoma/hexagon-grids-for-adobe-illustrator#1]
Hello! First, thank you for this great script. It works brilliantly and will save me so much time and pain making clean illustrator paths for hex grids in the future. 

I was wondering if it would be possible include support for other common shapes as well? I'm thinking especially about squares. 

Thanks again!

**Comment by jsoma** [comment]
The script can be a little finicky, but I'm keeping my fingers crossed it works for you! For squares and such, I recommend doing it the good old-fashioned way - I think this video should lend a hand: https://www.youtube.com/watch?v=gZ_sP9kLhGs
