### ISSUE TITLE
Remove strokes created by script?

### ISSUE THREAD

**Issue by tophneal** [jsoma/hexagon-grids-for-adobe-illustrator#2]
Love this script! A serious life/time saver for this kind of thing. Unfortunately, I didn't notice stroked would be applied to the shapes created by the script, and I'd like to remove them. However, Ai indicates there are no strokes what-so-ever anywhere in my file. How can I remove these strokes?

**Comment by tophneal** [comment]
I'll close this, I didn't realize that there was no stroke. What I thought were strokes was just a slight overlap of the shapes, combined with the lowered opacity. I set opacity of all shapes to 100% and the problem is now resolved.

**Comment by jsoma** [comment]
Glad it worked out! Yeah, there's a bit of weirdness and inexactness that goes on in there, haven't taken the time to sit down and make sure it's all optimal.
